server.port=3333
spring.application.name=api-gateway

spring.cloud.compatibility-verifier.enabled=false

# Route 1 - Routing Engine
spring.cloud.gateway.server.webflux.routes[0].id=routing-service-route
spring.cloud.gateway.server.webflux.routes[0].uri=https://routing-engine-k7di.onrender.com
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/route/**

# Route 2 - Auth Service
spring.cloud.gateway.server.webflux.routes[1].id=auth-service-route
spring.cloud.gateway.server.webflux.routes[1].uri=https://codeoptimizer-ai.onrender.com
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/auth/**

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
