server.port=8761
spring.application.name=service-registry

# Tell this service not to register with itself since it IS the registry server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false